apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-api-deployment
  labels:
    app: flight-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-api
  template:
    metadata:
      labels:
        app: flight-api
    spec:
      containers:
      - name: flight-api
        image: alisvlasova/flight-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/onpu"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "174180183"
        - name: SERVER_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: flight-api-service
spec:
  type: NodePort
  selector:
    app: flight-api
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080